[package]
name = "mnist-cli-gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.5.9", features=["derive"]}
anyhow = "1.0.86"
#pytorch rust
tch = "~0.16.0"