name: Rust CI/CD Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022, macOS-latest]
        rust: [stable, nightly]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: clippy, rustfmt
          override: true
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: check
      #     args: --features download-libtorch

      - name: update linux
        if: [${{ matrix.os == 'ubuntu-latest' }}]
        run: sudo apt update 
      - name: update Rust
        run: make install
      - name: Check Rust versions
        run: make rust-version
      - name: Format
        run: make format
      - name: Lint
        run: make lint
      - name: Test
        run: make test
    
